// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::driveBaseSubFrontLeftTalon;
std::shared_ptr<CANTalon> RobotMap::driveBaseSubBackLeftTalon;
std::shared_ptr<CANTalon> RobotMap::driveBaseSubFrontRightTalon;
std::shared_ptr<CANTalon> RobotMap::driveBaseSubBackRightTalon;
std::shared_ptr<RobotDrive> RobotMap::driveBaseSubRobotDrive;
std::shared_ptr<CANTalon> RobotMap::shooterSubShooterTalon;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    //LiveWindow *lw = LiveWindow::GetInstance();

    driveBaseSubFrontLeftTalon.reset(new CANTalon(1));
    //lw->AddActuator("DriveBaseSub", "FrontLeftTalon", driveBaseSubFrontLeftTalon);
    
    driveBaseSubBackLeftTalon.reset(new CANTalon(2));
    //lw->AddActuator("DriveBaseSub", "BackLeftTalon", driveBaseSubBackLeftTalon);
    
    driveBaseSubFrontRightTalon.reset(new CANTalon(3));
    //lw->AddActuator("DriveBaseSub", "FrontRightTalon", driveBaseSubFrontRightTalon);
    
    driveBaseSubBackRightTalon.reset(new CANTalon(4));
    //lw->AddActuator("DriveBaseSub", "BackRightTalon", driveBaseSubBackRightTalon);
    
    driveBaseSubRobotDrive.reset(new RobotDrive(driveBaseSubFrontLeftTalon, driveBaseSubBackLeftTalon,
              driveBaseSubFrontRightTalon, driveBaseSubBackRightTalon));
    
    driveBaseSubRobotDrive->SetSafetyEnabled(false);
        driveBaseSubRobotDrive->SetExpiration(0.1);
        driveBaseSubRobotDrive->SetSensitivity(0.5);
        driveBaseSubRobotDrive->SetMaxOutput(1.0);

    shooterSubShooterTalon.reset(new CANTalon(5));
    //lw->AddActuator("ShooterSub", "ShooterTalon", shooterSubShooterTalon);
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
