// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveCommand.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveCommand::DriveCommand(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveBaseSub.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	xAxis = 0;
	yAxis = 0;
	rotAxis = 0;
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DriveCommand::Initialize() {
	//xaxis is 1,yaxis is 2, rotaxis is 3
	xAxis = Robot::oi->getDriverJoystick()->GetRawAxis(0);
	yAxis = Robot::oi->getDriverJoystick()->GetRawAxis(1);
	rotAxis = Robot::oi->getDriverJoystick()->GetRawAxis(4);
	//Creating Deadzones to allow slight movement of controller without robot moving.
	if(xAxis > -.20 && xAxis < .20){
		xAxis = 0;
	}else{
		xAxis = xAxis * fabs(xAxis);
	}
	if(yAxis > -.20 && yAxis < .20){
		yAxis = 0;
	}else{
		yAxis = yAxis * fabs(yAxis);
	}
	if(rotAxis > -.20 && rotAxis < .20){
		rotAxis = 0;
	}else{
		rotAxis = rotAxis * fabs(rotAxis);
	}
	Robot::driveBaseSub->mechanimDrive(xAxis,yAxis,rotAxis,0);


}

// Called repeatedly when this Command is scheduled to run
void DriveCommand::Execute() {

}

// Make this return true when this Command no longer needs to run execute()
bool DriveCommand::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void DriveCommand::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveCommand::Interrupted() {

}
